### ISSUE TITLE
GetKey function issue

### ISSUE THREAD

**Issue by Jacobg1995** [Cryptolens/cryptolens-nodejs#25]
GetKey() method does not currently work.

line 77 of Key.js:
const license = JSON.parse(Buffer.from(helpers.GetValueCaseInsensitive(res,"licenseKey"), "base64").toString("utf-8"));

res is undefined, need to either replace line 61 const name with res instead of body or fix line 77 to have body instead of res...

**Comment by artemlos** [comment]
@Jacobg1995 Thanks for reporting this! It should now be fixed.

Have a nice weekend!
Artem
