### ISSUE TITLE
 GetMachineCode

### ISSUE THREAD

**Issue by roelvanegmond** [Cryptolens/cryptolens-nodejs#8]
GetMachineCode is not documented, I found it by looking at the code but I can't call it when I included the helpers as described in the documentation.

const Helpers = require('cryptolens').Helpers;

Expected that Helpers.GetMachineCode() would work.

**Comment by artemlos** [comment]
Thanks for the feedback! The documentation is now updated: https://github.com/Cryptolens/cryptolens-nodejs/commit/0b4cd1c94140dfb825545462086cfeefadd7d25c

@roelvanegmond
