### ISSUE TITLE
Active promise always resolves even request failure

### ISSUE THREAD

**Issue by roelvanegmond** [Cryptolens/cryptolens-nodejs#9]
var result = Key.Activate(auth, RSAPubKey, fake, "fake, "test");

Maybe it is on purpose so I am not stating that it is wrong but I would expect the promise to get rejected when the request fails. Allowing the use of result.catch()

**Comment by roelvanegmond** [comment]
In addition, maybe related. Using the example provided in the documentation the  console.log(license.Created); gets triggered twice

**Comment by artemlos** [comment]
This is now fixed in the latest commit: https://github.com/Cryptolens/cryptolens-nodejs/commit/b3c7140048f783b4411070342eb4db6f8dfb9ddf

Thanks for the feedback!

@roelvanegmond
